### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [IgorKruchinin/AchieApp#2]
1.3 failed https://gitlab.com/fdroid/fdroiddata/-/jobs/4509355974#L462

Let's add Java 17: https://gitlab.com/fdroid/fdroiddata/-/commit/02084bc45de62f6799d35ac39630d4070967a720

But now it fails to be repro: https://gitlab.com/fdroid/fdroiddata/-/jobs/4510797064#L340

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/fae542ed3f8cd7b394da89ef448970c9098ab57b

**Comment by licaon-kter** [comment]
@IgorKruchinin you did build your APK with Java17, right?

**Comment by licaon-kter** [comment]
Diff log: [achie1.log](https://github.com/IgorKruchinin/AchieApp/files/11814233/achie1.log)

@IgorKruchinin you are sure that your 1.3 APK is built from a64af0dc86ea677bd3f3861a7fe085c88d25732f ?

@linsui thoughts?

**Comment by linsui** [comment]
I also doubt that the apk is built from the same commit.

**Comment by IgorKruchinin** [comment]
I will check correctness of pushing via android studio

**Comment by IgorKruchinin** [comment]
Pushing stucks in "Writing objects: 100%"

**Comment by IgorKruchinin** [comment]
> Pushing stucks in "Writing objects: 100%"

Solved

**Comment by IgorKruchinin** [comment]
I am cloned repository again and built app from the cloned sources and changed the file into Github release

**Comment by licaon-kter** [comment]
Ok, the good news is that your APKs are reproducible... between themselves.

The bad news is that... this second one, by the fact above heh, is still not repro when compared with the one we build locally.

Can you `git status` check which commit is used?

Can you list all your Java versions installed and uninstall all those that are not used?

**Comment by IgorKruchinin** [comment]
![Screenshot_20230621_150850](https://github.com/IgorKruchinin/AchieApp/assets/93050201/2235cb49-5597-482e-9143-349423411e6d)
![Screenshot_20230621_151244](https://github.com/IgorKruchinin/AchieApp/assets/93050201/6c05cfdc-b18c-499f-a58e-365d4d0e1b3f)

**Comment by IgorKruchinin** [comment]
Screenshots with git status and list with jdk installed in my system

**Comment by licaon-kter** [comment]
@IgorKruchinin my bad, not status, I meant: `git log|head`

**Comment by IgorKruchinin** [comment]
![Screenshot_20230621_152003](https://github.com/IgorKruchinin/AchieApp/assets/93050201/289cb43f-f23d-400c-aa77-091919641875)

**Comment by IgorKruchinin** [comment]
commit 6cffc06fa0ddaa738b1d8a214335e0d6952b0fae
Merge: efe0f72 7809848
Author: user <igoryanbex@yandex.ru>
Date:   Wed Jun 21 12:01:28 2023 +0400

    Merge remote-tracking branch 'origin/master'

commit 78098487b8d8d3e150b73577ac3ab11cae765bc6
Author: IgorKruchinin <93050201+IgorKruchinin@users.noreply.github.com>
Date:   Wed Jun 21 09:29:57 2023 +0400

**Comment by licaon-kter** [comment]
Ok...so... not the same commit that we've built from: https://gitlab.com/fdroid/fdroiddata/-/commit/fae542ed3f8cd7b394da89ef448970c9098ab57b#2d382e438c7c481869a0eb33208bd141c8bcdcac_45_46

Let me try https://github.com/IgorKruchinin/AchieApp/commit/6cffc06fa0ddaa738b1d8a214335e0d6952b0fae then

**Comment by licaon-kter** [comment]
@IgorKruchinin ummm better fix this first :( 
```
Could not build app ru.ikkui.achie: supplied reference binary signed with 5753fa3e344f569851c05db41bd15614569f916e3a020bfbe41d5f96d52f681f instead of with ['90332e2c1c4b2ebe01e391855c37b901b49b6c7882fb9a312b24e548122b1c20']
```

...your new APKs are not signed with the same key

**Comment by IgorKruchinin** [comment]
But I have not old keystore because I am building in a new computer

**Comment by licaon-kter** [comment]
oh :(

This will complicate things....

**Comment by IgorKruchinin** [comment]
May I publish new versions in this case?

**Comment by licaon-kter** [comment]
We'll need to amend the recipe with the new signature... remove old versions. Etc.

Users will be stuck with the old version unless they uninstall then reinstall. :(

On a first try it might be reproducible, I've run the build again. Brb

**Comment by licaon-kter** [comment]
Yup, it is reproducible.

Now, you have a new key. Is this key gonna be taken care of better than the last one? :)

**Comment by IgorKruchinin** [comment]
I hope

**Comment by IgorKruchinin** [comment]
Is this app builds successfully?

**Comment by licaon-kter** [comment]
Yes, it's fine.

**Comment by IgorKruchinin** [comment]
Is this problem solved?

**Comment by linsui** [comment]
So we need to disable all old versions and change to the new key? https://monitor.f-droid.org/builds/log/ru.ikkui.achie/9#site-footer

**Comment by IgorKruchinin** [comment]
Yes
